@url = http://localhost:5229

############# URLS ################
### CREATE
POST {{url}}/api/url
content-type: application/json

{
    "url": "https://google.com",
    "title": "Jooje"
}

### FIND BY SHORT URL
GET {{url}}/api/url/qDJo HTTP/1.1

### GET TOP 10 URL
GET {{url}}/api/url HTTP/1.1

### GET BY ID

GET {{url}}/api/url/find/23 HTTP/1.1

### DELETE

DELETE {{url}}/api/url/24 HTTP/1.1
content-type: application/json

############# USERS ###############

POST {{url}}/api/user
content-type: application/json

{
    "Username": "Hello!",
    "Email": "joaospereira963@gmail.com",
    "Password": "TestPassword87!"
}