@url = http://localhost:5229

### CREATE URL
POST {{url}}/api/url
content-type: application/json

{
    "url": "https://google.com",
    "title": "Jooje"
}

### FIND BY URL
GET {{url}}/api/url/qDJo HTTP/1.1

### GET TOP 10 URL
GET {{url}}/api/url HTTP/1.1

### GET BY ID

GET {{url}}/api/url/find/23 HTTP/1.1

### DELETE URL

DELETE {{url}}/api/url/24 HTTP/1.1
content-type: application/json